# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YouView.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 785)
        MainWindow.setMinimumSize(QtCore.QSize(900, 785))
        MainWindow.setMaximumSize(QtCore.QSize(900, 785))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/atom_python/section6/resource/Youtube-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(MainWindow)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 211, 471))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(5, 17, 200, 200))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:/atom_python/section6/resource/6bed4687-5e74-40b2-8dfb-c6e74dd960c6_200x200.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.loginButton = QtWidgets.QPushButton(self.groupBox)
        self.loginButton.setGeometry(QtCore.QRect(44, 207, 121, 41))
        self.loginButton.setObjectName("loginButton")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.groupBox)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 262, 192, 201))
        self.calendarWidget.setObjectName("calendarWidget")
        self.groupBox_2 = QtWidgets.QGroupBox(MainWindow)
        self.groupBox_2.setGeometry(QtCore.QRect(230, 10, 661, 471))
        self.groupBox_2.setObjectName("groupBox_2")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.groupBox_2)
        self.webEngineView.setGeometry(QtCore.QRect(10, 17, 641, 445))
        self.webEngineView.setUrl(QtCore.QUrl("about:blank"))
        self.webEngineView.setObjectName("webEngineView")
        self.line = QtWidgets.QFrame(MainWindow)
        self.line.setGeometry(QtCore.QRect(10, 490, 881, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_3 = QtWidgets.QGroupBox(MainWindow)
        self.groupBox_3.setGeometry(QtCore.QRect(460, 510, 430, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 20, 411, 191))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.groupBox_4 = QtWidgets.QGroupBox(MainWindow)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 510, 430, 221))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_2.setGeometry(QtCore.QRect(10, 34, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 85, 71, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 135, 71, 16))
        self.label_4.setObjectName("label_4")
        self.urlTextEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.urlTextEdit.setGeometry(QtCore.QRect(80, 30, 251, 21))
        self.urlTextEdit.setObjectName("urlTextEdit")
        self.previewButton = QtWidgets.QPushButton(self.groupBox_4)
        self.previewButton.setGeometry(QtCore.QRect(340, 30, 75, 31))
        self.previewButton.setObjectName("previewButton")
        self.fileNavButton = QtWidgets.QToolButton(self.groupBox_4)
        self.fileNavButton.setGeometry(QtCore.QRect(340, 80, 75, 31))
        self.fileNavButton.setObjectName("fileNavButton")
        self.streamComboBox = QtWidgets.QComboBox(self.groupBox_4)
        self.streamComboBox.setGeometry(QtCore.QRect(80, 130, 335, 21))
        self.streamComboBox.setObjectName("streamComboBox")
        self.startButton = QtWidgets.QPushButton(self.groupBox_4)
        self.startButton.setGeometry(QtCore.QRect(250, 170, 75, 35))
        self.startButton.setObjectName("startButton")
        self.endButton = QtWidgets.QPushButton(self.groupBox_4)
        self.endButton.setGeometry(QtCore.QRect(340, 170, 75, 35))
        self.endButton.setObjectName("endButton")
        self.pathTextEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.pathTextEdit.setGeometry(QtCore.QRect(80, 80, 251, 21))
        self.pathTextEdit.setObjectName("pathTextEdit")
        self.label_5 = QtWidgets.QLabel(MainWindow)
        self.label_5.setGeometry(QtCore.QRect(10, 744, 91, 16))
        self.label_5.setObjectName("label_5")
        self.progressBar = QtWidgets.QProgressBar(MainWindow)
        self.progressBar.setGeometry(QtCore.QRect(100, 740, 341, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_2 = QtWidgets.QProgressBar(MainWindow)
        self.progressBar_2.setGeometry(QtCore.QRect(548, 740, 341, 23))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.label_6 = QtWidgets.QLabel(MainWindow)
        self.label_6.setGeometry(QtCore.QRect(458, 744, 91, 16))
        self.label_6.setObjectName("label_6")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "기본정보"))
        self.loginButton.setText(_translate("MainWindow", "Login"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Player"))
        self.groupBox_3.setTitle(_translate("MainWindow", "로그"))
        self.groupBox_4.setTitle(_translate("MainWindow", "다운로드 URL 및 저장 위치"))
        self.label_2.setText(_translate("MainWindow", "Video URL : "))
        self.label_3.setText(_translate("MainWindow", "Save  To   :"))
        self.label_4.setText(_translate("MainWindow", "Stremeaing:"))
        self.previewButton.setText(_translate("MainWindow", "확인"))
        self.fileNavButton.setText(_translate("MainWindow", "..."))
        self.startButton.setText(_translate("MainWindow", "START"))
        self.endButton.setText(_translate("MainWindow", "END"))
        self.label_5.setText(_translate("MainWindow", "브라우저 로딩"))
        self.label_6.setText(_translate("MainWindow", "브라우저 로딩"))
from PyQt5 import QtWebEngineWidgets


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
